version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: c:\projects
install:

  - cd c:\projects\build

  - git submodule update --init --recursive

  - cd c:\projects

build_script:
- cmd: >-
    nuget restore c:\projects\build\build.sln

    msbuild c:\projects\build\build.sln /p:Configuration="Release" /verbosity:quiet

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: uc-serialization
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false